# what is the goal of your  workflow
# Goal: Whenever someone chnages the python code, 
# the linter will check if the syntax format indentation is corret or not


name: Auto Linter
on:
  push:
    paths: "*.py"
jobs:
  code:
    runs-on: ubuntu-latest
    # this step automaticaly clone the code of the current branch into the runner
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
        # this step will install the linter
      - name: Install Linter
        run: pip install ruff
